#include <stdbool.h>
#include "map.h"
#include "config.h"

#define L {LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT,LIMIT}
#define E {LIMIT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,LIMIT}

int worldMap[MAP_HEIGHT][MAP_WIDTH] = {
    L,
    E, E, E, E, E,
    E, E, E, E, E,
    E, E, E,
    L,
};

#undef L
#undef E
